#!/bin/bash
#honk-ceo 1000 (max run) 5 (start down percent) 5 (down increment) 70 (up decrement) 3 (up decrement)
set -x
usage(){
    printf '%s\n' "$*" >&2
    cat >&2
    exit 1
}<<\EOF
honk-ceo _maxrun_ _startdowndist_ _downincrement_ _startupdist_ _updecrement_
maxrun - max runs before exiting
startdowndist- down distribution starting value
downincrement- down distribution decrementing value
5 5 means it'll first be 5 then 10 then 15
similar for startupdist and updecrement
EOF

die(){
    printf '%s\n' "$*" >&2
    exit 1
}

cleanup(){
    pkill --exact honk-manager
}

maxrun=1000
downdist=5
downincrement=5
updist=60
updecrement=0

totalservers=8

case $# in
    5)
	updecrement=$5
	;&
    4)
	updist=$4
	;&
    3)
	downincrement=$3
	;&
    2)
	downdist=$2
	;&
    1)
	maxrun=$1
	;;
    0)
	;;
    *)
	usage eeeeeeeeeeeeeeeeeeeeeeeeeeee
	;;
esac
. ~/allthingshonk/activate
trap 'cleanup' EXIT

while (( downdist<90 || updist>10 )); do
    if (( downdist < 90 )); then
	downdist=$(( downdist + downincrement ));
	if (( downdist >= 90 )); then break; fi
    fi
    # if (( startupdist > 10 )); then
    # 	startupdist=$(( startupdist - updecrement ));
    # 	if (( startupdist < 10 )); then break; fi
    # fi
    honk-manager "$totalservers" "$downdist" "$updist" 60 3 "$maxrun"
done


