#!/bin/bash
set -x
usage(){
    printf '%s\n' "$*" >&2
    cat >&2
    exit 1
}<<\EOF
honk-servers _totalservers_ _honkdistribution_
EOF

die(){
	printf '%s\n' "$*" >&2
	exit 1
}

get_servers(){
    #$1 folders stored in servers array
    for (( i=0; i<"$totalservers"; i++)); do
	port=$((5000+i))
	up_servers=("${up_servers[@]}" "$port")
    done
}

honk_servers(){
    #servers honk aggressively
     for server in "${up_servers[@]}"; do
	 if (( RANDOM%100 <= honkdistribution )); then
	     honk-aggressively "$server"
	 fi
     done
}

total_servers=()
totalservers=20
honkdistribution=60
honktime=3

#exec 3>>~/allthingshonk/honk.log

case $# in
    3)
	honktime=$3
	;&
    2)
	(( $2 < 100 && $2 > 1 )) || usage
	honkdistribution=$2
	;&
    1)
	(( $1 < 1000 && $1 > 1 )) || usage "no of servers"
	totalservers=$1
	;;
     *)
	 usage
	 ;;
esac

get_servers
while sleep "$honktime"; do
    honk_servers "$totalservers" "$honkdistribution" # 1>&3 2>&1
done

