#!/bin/bash

maxrun=100
downdist=5
downincrement=5
updist=60
updecrement=0
totalservers=8

usage(){
    printf '%s\n' "$*" >&2
    cat >&2
    exit 1
}<<EOF
honk-ceo [-t #servers] [-m maxrun] [-d downdist] [-D downincrement] [-u updist] [-U updecrement]
-t, #servers	no of servers (default $totalservers)
-m, maxrun	max runs before exiting (default $maxrun)
-d, downdist	down distribution starting value (default $downdist)
-D, downincrement	(+ve)change in downdist for each run (default $downincrement)
-u, updist	up-distribution starting value (default $updist)
-U, updecrement	(-ve)change in updist for each run (default $updecrement)
EOF

die(){
    printf '%s\n' "$*" >&2
    exit 1
}

cleanup(){
    pkill --exact honk-manager
}

while getopts 'm:d:u:t:D:U:' opt; do
    case $opt in
	m)
	    maxrun=$OPTARG
	    ;;
	d)
	    downdist=$OPTARG
	    ;;
	u)
	    updist=$OPTARG
	    ;;
	t)
	    totalservers=$OPTARG
	    ;;
	D)
	    downincrement=$OPTARG
	    ;;
	U)
	    updecrement=$OPTARG
	;;
	"?")
	    usage
	    ;;
	*)
	    printf '%s\n' "impossible" >&2
	    usage
	    ;;
    esac
done

# shellcheck source=activate
. ~/allthingshonk/activate
trap 'cleanup' EXIT

while (( downdist<90 || updist>10 )); do
    if (( downdist < 90 )); then
	downdist=$(( downdist + downincrement ));
	if (( downdist >= 90 )); then break; fi
    fi
    if (( updist > 10 )); then
    	updist=$(( updist - updecrement ));
    	if (( updist < 10 )); then break; fi
    fi
    set -x
    honk-manage purge-all
    honk-manager "$totalservers" "$downdist" "$updist" 60 3 "$maxrun" || exit 1
    set +x
done
