#!/bin/bash
usage(){
    cat >&2
    exit 1
}<<\EOF
honk-aggressively domain username [password]
post a long message on the domain.
default password is same as username.
EOF

die(){
    printf "%s\n" "$@" >&2
    exit 1
}

lorem(){
    chars=$(( RANDOM % 1000 ))
    LC_ALL=C grep -"m$chars" -aEo '[[:alnum:]]' /dev/urandom | tr -d '\n' | paste -s
}

if (( $# < 2 )); then
    usage
fi

domain=$1
username=$2
password=$username
shift 2
if (( $# > 0 )); then
    password=$3
    shift
fi
# shellcheck source=honk-manage.conf
. ~/allthingshonk/honk-manage.conf

tmpfile="/tmp/honking.$$.html"
#trap 'rm "$tmpfile"' EXIT
set -x
csrf=$(honk-login "$domain" "$username" "/")
lorem | CURL -i -F "noise=<-" "https://$domain/honk"> "$tmpfile"
status=$?

if head -n1 "$tmpfile" | grep -qF 'HTTP/1.1 303 See Other'; then
    awk -v"host=$domain" '/Location:/{printf "%s%s\n", host, $2}' "$tmpfile"
else
    status=1
fi

exit "$status"

