#!/bin/bash

# shellcheck source=honk-manage.conf
. ~/allthingshonk/honk-manage.conf

usage(){
    cat >&2
    exit 1
}<<EOF
honk-login domain username [csrf_page]
saves login cookie to $rundir/cookie-\$domain-\$username
if csrf_page is specified, get csrf token from that page.

do not pass scheme:// on domain, as we use the domain name on cookie file.
Thus, it'll always be https://domain
EOF

if (( $# < 2 )); then
    usage
fi

domain=$1
username=$2
password=$username
if [[ $domain =~ *"://"* ]]; then
    die "domain can't contian scheme://"
fi
shift 2

tmpfile="/tmp/honk-login.$$.html"
trap 'rm "$tmpfile"' EXIT
set -x

CURL -F "username=$username" -F "password=$password" "https://$domain/dologin" > "$tmpfile" || die "couldn't login"
status=$?

csrf_page=false
if (( $# > 0 )) ; then
    csrf_page=$1
    shift
fi

if [[ $csrf_page == false ]]; then
    exit $status
fi

CURL "https://$domain$csrf_page" > "$tmpfile" || die "couldn't connect"

awk -F'"' 'BEGIN{e=1}
/<input type="hidden" name="CSRF"/{print $6; e=0; exit}
END{exit e}' "$tmpfile"
